### PR TITLE
Added installion instructions

### PR DESCRIPTION
**Pull request by Haiz14**

### CODE REVIEW

**Review by Damaj301damaj-lol — CHANGES_REQUESTED** [review]
> curl -s https://github.com/UrNightmaree/startmux | bash

Not the way to do it, please just use `curl https://raw.githubusercontent.com/UrNightmaree/startmux/main/startmux.sh | bash`

**Comment by Damaj301damaj-lol** [comment]
> press ctrl+c

Killing the program is probably not key, the program should save the changes then ask the user if they want them applied, not otherwise.

**Comment by Damaj301damaj-lol** [comment]
Please tell me the commit above was a joke

**Comment by Haiz14** [comment]
I never used pr just testing things out

**Comment by Haiz14** [comment]
I was wondering how pr update gets merged it's automatic

**Comment by Damaj301damaj-lol** [comment]
> I was wondering how pr update gets merged it's automatic

They don't, they can be made, but nobody does

**Comment by Haiz14** [comment]
No no I update the pr code, and it got merged to the pr automatically. Should be more like when I update a branch, the pr gets update.

**Comment by asumbek** [comment]
I'll close this PR since Startmux isn't ready for use yet. 😅

**Pull request closed without merging**
